name: classride_app_project2
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/aboutus.jpg
