name: classride_app_project2
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19-nullsafety.5
  http: ^0.13.6
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/aboutus.jpg
